# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Test getNbRows()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#getNbRows --file pom.xml

      - name: Test getNbColumns()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#getNbColumns --file pom.xml

      - name: Pretty test
        run: mvn -B test -Dtest=PrettySliding2DArrayTest#prettyTest --file pom.xml

      - name: Test get()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#get --file pom.xml

      - name: Test slide()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#slide --file pom.xml

      - name: Test slideUp()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#slideUp --file pom.xml

      - name: Test slideDown()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#slideDown --file pom.xml

      - name: Test slideLeft()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#slideLeft --file pom.xml

      - name: Test slideRight()
        run: mvn -B test -Dtest=PointSliding2DArrayTest#slideRight --file pom.xml

      - name: Huge test
        run: mvn -B test -Dtest=HugeWorldSliding2DArrayTest --file pom.xml

    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
